### ISSUE TITLE
Build failure on x86_64-linux: `error: 'RawCompressFromIOVec' is not a member of 'snappy'`

### ISSUE THREAD

**Issue by samuela** [google/jax#14795]
### Description

I'm seeing the following error when attempting to build jaxlib v0.4.4 from source on x86_64-linux:
```
ERROR: /build/output/external/org_tensorflow/tensorflow/tsl/platform/default/BUILD:314:11: Compiling tensorflow/tsl/platform/default/port.cc failed: (Exit 1): gcc failed: error executing command /nix/store/bfbp3ypd9nm3fapz634gvvs738blrl0y-gcc-wrapper-12.2.0/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 ... (remaining 160 arguments skipped)
external/org_tensorflow/tensorflow/tsl/platform/default/port.cc: In function 'bool tsl::port::Snappy_CompressFromIOVec(const iovec*, size_t, std::string*)':
external/org_tensorflow/tensorflow/tsl/platform/default/port.cc:328:11: error: 'RawCompressFromIOVec' is not a member of 'snappy'; did you mean 'RawUncompressToIOVec'?
  328 |   snappy::RawCompressFromIOVec(iov, uncompressed_length, &(*output)[0],
      |           ^~~~~~~~~~~~~~~~~~~~
      |           RawUncompressToIOVec
At global scope:
cc1plus: note: unrecognized command-line option '-Wno-unknown-warning-option' may have been intended to silence earlier diagnostics
Target //build:build_wheel failed to build
```
This can be reproduced by running `nix-build -A python3Packages.jaxlib` from a checkout of this PR: https://github.com/NixOS/nixpkgs/pull/219778. I've found that this error applies to both the CPU and GPU-enabled builds of jaxlib.

FWIW I'm attempting to build with snappy 1.1.9. What are the supported snappy versions? How can I build from source successfully?

### What jax/jaxlib version are you using?

jaxlib v0.4.4

### Which accelerator(s) are you using?

n/a

### Additional system info

NixOS

### NVIDIA GPU info

n/a

**Comment by samuela** [comment]
It's also worth noting that jaxlib v0.3.22 does have any issue compiling against this exact same version of snappy... perhaps something has changed in the source since then?

**Comment by samuela** [comment]
Hi @hawkinsp , thanks for your response! Following your feedback, I tried building with the vendored version of snappy (by removing snappy from `TF_SYSTEM_LIBS`). However, now I'm seeing a new error:
```
ERROR: /build/output/external/org_tensorflow/tensorflow/tsl/platform/default/BUILD:314:11: Compiling tensorflow/tsl/platform/default/port.cc failed: (Exit 1): gcc failed: error executing command /nix/store/bfbp3ypd9nm3fapz634gvvs738blrl0y-gcc-wrapper-12.2.0/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 ... (remaining 156 arguments skipped)
external/org_tensorflow/tensorflow/tsl/platform/default/port.cc:41:10: fatal error: snappy.h: No such file or directory
   41 | #include "snappy.h"
      |          ^~~~~~~~~~
compilation terminated.
Target //build:build_wheel failed to build
```
(for context, commit removing snappy is available here: https://github.com/NixOS/nixpkgs/pull/219778/commits/212ee957f3363e97423fbe116bdcad1e10ae0690)

How can I build from source with the vendored snappy?

**Comment by hawkinsp** [comment]
It should work without doing anything. Sometimes `bazel clean` helps if you have changed the repositories around. Try running that and retry?

**Comment by samuela** [comment]
I completely erased my bazel set up in between builds. Perhaps something else?

**Comment by samuela** [comment]
(FWIW: I tried upgrading bazel 5->6 to see if that made any difference but i got a different error:
```
ERROR: /build/output/external/org_tensorflow/tensorflow/compiler/xla/pjrt/BUILD:470:11: in cc_library rule @org_tensorflow//tensorflow/compiler/xla/pjrt:pjrt_future: target '@tf_runtime//:support' is not visible from target '@org_tensorflow//tensorflow/compiler/xla/pjrt:pjrt_future'. Check the visibility declaration of the former target if you think the dependency is legitimate
```
but that's really a tangent)

**Comment by hawkinsp** [comment]
Hmm. I'm pretty confident it works because I literally just rebuilt from head myself a few minutes ago on a clean ubuntu vm.

(Note `bazel clean` removes cached bazel state, not bazel itself).

**Comment by samuela** [comment]
> Hmm. I'm pretty confident it works because I literally just rebuilt from head myself a few minutes ago on a clean ubuntu vm.

Weird... Maybe there's something wonky in the diff between current `main` and `refs/tags/jaxlib-v0.4.4`?

> (Note bazel clean removes cached bazel state, not bazel itself).

Yes, to be more precise: Nix provides a hermetic build environment on every run so the bazel installation and bazel cache files are completely fresh on every invocation. So no side effectful things to worry about :)

**Comment by samuela** [comment]
Snappy just released a new version: https://github.com/google/snappy/releases/tag/1.1.10. Perhaps that could fix the build? I'll give it a shot tomorrow.

**Comment by hawkinsp** [comment]
Yup, I asked them and they very nicely made a new release. I think that will do the trick.

**Comment by samuela** [comment]
Oh, thank you so much @hawkinsp ! I really appreciate it!

**Comment by samuela** [comment]
Ok, can confirm that it builds now! thanks again @hawkinsp! ([PR for context](https://github.com/NixOS/nixpkgs/pull/219778))
