### ISSUE TITLE
custom_call() got an unexpected keyword argument 'out_types'

### ISSUE THREAD

**Issue by ecignoni** [google/jax#18419]
### Description

I have encountered this problem today: when calling a custom CPU extension for JAX I got the following exception:

```bash
TypeError: custom_call() got an unexpected keyword argument 'out_types'
```
I investigated a bit and I've seen [here](https://github.com/google/jax/blob/e66f4e94c4841cca762b09a6147f12963f14cec1/jaxlib/hlo_helpers.py#L134C8-L134C8) that probably `out_types` should be changed into `result_types`.
If I do that I don't get that error anymore, but a new one:

```bash
File ~/software/miniconda3/envs/gpx-env/lib/python3.10/site-packages/jax/_src/interpreters/mlir.py:602, in wrap_singleton_ir_values(x)
    601 """Adds a consistent tuples to a mixture of tupled and untuple values."""
--> 602 return (x,) if isinstance(x, ir.Value) else tuple(x)

TypeError: 'CustomCallOp' object is not iterable
```

direct cause of this

```bash
ValueError: Output of translation rule must be iterable: a:i64[291753] = retain_full_residues b c 291753 64504, got output (<jaxlib.mlir.dialects._stablehlo_ops_gen.CustomCallOp object at 0x148fb0ee3010>,)
```

that I don't know how to solve.
I got this error with jax v0.4.20 and jaxlib v0.4.20.
My code works with no problems with jax v0.4.13 and jaxlib v0.4.13

### What jax/jaxlib version are you using?

jax v0.4.20 jaxlib v0.4.20

### Which accelerator(s) are you using?

CPU

### Additional system info

python version 3.10.13,  rocky linux 8.8

**Comment by ecignoni** [comment]
I've solved the issue by myself looking [here](https://github.com/google/jax/commit/24f9011d49f974fa24613206c5af774089ecf346#diff-c3e9738463b09bd238dfa8c352c3d18cb240d573d003b4a14d752dcf24d8d946), I should have also added `.results` to the return value.
