### ISSUE TITLE
Jax windows building failure due to dependent on tpu_initializer_helper

### ISSUE THREAD

**Issue by cloudhan** [google/jax#10687]
Currently, building jaxlib from latest main branch results in the following error:
```
external/org_tensorflow/tensorflow/core/tpu/tpu_initializer_helper.cc(18): fatal error C1083: Cannot open include file: 'dirent.h': No such file or directory
```
---
```
bazel --output_user_root=C:/bazel_output_root cquery --verbose_failures=true --config=mkl_open_source_only --config=cuda 'allpaths(//build:build_wheel, @org_tensorflow//tensorflow/core/tpu:tpu_initializer_helper)'
```

shows (a linear dep visualized from svg graph)
```
@org_tensorflow//tensorflow/core/tpu:tpu_initializer_helper (18240d3)
@org_tensorflow//tensorflow/compiler/xla/pjrt:tpu_client (18240d3)
@org_tensorflow//tensorflow/compiler/xla/python:xla_extension.so (18240d3)
@org_tensorflow//tensorflow/compiler/xla/python:xla_extension_filegroup (18240d3)
@org_tensorflow//tensorflow/compiler/xla/python:xla_extension_pyd_copy (18240d3)
@org_tensorflow//tensorflow/compiler/xla/python:xla_extension.pyd (18240d3)
@org_tensorflow//tensorflow/compiler/xla/python:xla_extension (18240d3)
@org_tensorflow//tensorflow/compiler/xla/python:xla_client (18240d3)
//build:build_wheel (18240d3)
```

The edge from `tpu_client` to `tpu_initializer_helper` is introduced in https://github.com/tensorflow/tensorflow/commit/8c78a5a5f6d6e510f5bbc327b2efaeeaea4f3796

**Comment by hawkinsp** [comment]
I think the easiest fix would be to not even build the TPU support at all on Windows, because there are no Windows machines with TPUs. Currently the support gets built but cannot be used, which is somewhat pointless.

**Comment by hawkinsp** [comment]
I think this is fixed at head: just don't pass `--enable_tpu` when building.
