### ISSUE TITLE
Jax profiling tracer - possible incompatibility with python 3.9(.12)

### ISSUE THREAD

**Issue by thibmonsel** [google/jax#11011]
Im following the documentation for jax [profiling](https://jax.readthedocs.io/en/latest/profiling.html).

Im executing the code
```
with jax.profiler.trace("/tmp/jax-trace", create_perfetto_link=True):
  # Run the operations to be profiled
  key = jax.random.PRNGKey(0)
  x = jax.random.normal(key, (5000, 5000))
  y = x @ x
  y.block_until_ready()
```
A perfetto link is opened beforehand)
The error found  : 
```
 File "/home/monsel/Desktop/neural_ode/train_node_hk.py", line 149, in <module>
    with jax.profiler.trace("/tmp/jax-trace", create_perfetto_link=True):
  File "/home/monsel/miniconda3/envs/ode2/lib/python3.9/contextlib.py", line 263, in helper
    return _GeneratorContextManager(func, args, kwds)
  File "/home/monsel/miniconda3/envs/ode2/lib/python3.9/contextlib.py", line 87, in __init__
    self.gen = func(*args, **kwds)
TypeError: trace() got an unexpected keyword argument 'create_perfetto_link'
```
It seems that jax profiler doesn't work with python 3.9.12.
```
python 
Python 3.9.12 (main, Apr  5 2022, 06:56:58) 
```
Otherwise, I find it unclear how to launch a profiler with perfetto for jax on my local machine.

**Comment by sharadmv** [comment]
The `create_perfetto_link` is a feature we just added and isn't in a release yet. You'll need to use JAX at HEAD until we make a new release. Sorry about the confusion.

**Comment by thibmonsel** [comment]
makes sense now thanks !
