### ISSUE TITLE
v0.3.0 build failure with CUDA support (CPU-only builds fine)

### ISSUE THREAD

**Issue by samuela** [google/jax#9534]
Please:

- [x] Check for duplicate issues.
- [x] Provide a complete example of how to reproduce the bug, wrapped in triple backticks like this:

Steps to reproduce:
* Clone https://github.com/NixOS/nixpkgs/pull/159099/commits/19c42cefd72befdbeab5b98c5534626d5905a8ce
* Update `pkgs/development/python-modules/jaxlib/default.nix` with these contents https://gist.github.com/samuela/931d7e29dd5e83ec5bf73de3bbc5b084.
* Run `NIX_PATH=.. nix-build -E "with import <nixpkgs> {}; python3Packages.jaxlib.override { cudaSupport = true; }"` inside your `nixpkgs` checkout.

Observe the failure:
```
ERROR: /build/output/external/org_tensorflow/tensorflow/compiler/xla/python/BUILD:206:11: Compiling tensorflow/compiler/xla/python/pprof_profile_builder.cc failed: (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -MD -MF ... (remaining 184 arguments skipped)
In file included from external/com_google_absl/absl/strings/str_format.h:76,
                 from external/org_tensorflow/tensorflow/compiler/xla/util.h:35,
                 from external/org_tensorflow/tensorflow/compiler/xla/python/pprof_profile_builder.cc:21:
external/com_google_absl/absl/strings/internal/str_format/arg.h: In instantiation of ‘constexpr absl::lts_20211102::FormatConversionCharSet absl::lts_20211102::str_format_internal::ArgumentToConv() [with Arg = google::protobuf::stringpiece_internal::StringPiece]’:
external/com_google_absl/absl/strings/str_format.h:257:46:   required by substitution of ‘template<class ... Args> using FormatSpec = absl::lts_20211102::str_format_internal::FormatSpecTemplate<(ArgumentToConv<Args>)()...> [with Args = {google::protobuf::stringpiece_internal::StringPiece}]’
external/org_tensorflow/tensorflow/compiler/xla/util.h:214:8:   required by substitution of ‘template<class ... Args> tensorflow::Status xla::InvalidArgument(absl::lts_20211102::FormatSpec<Args ...>&, const Args& ...) [with Args = {google::protobuf::stringpiece_internal::StringPiece}]’
external/org_tensorflow/tensorflow/compiler/xla/python/pprof_profile_builder.cc:71:71:   required from here
external/com_google_absl/absl/strings/internal/str_format/arg.h:305:54: error: no matching function for call to ‘FormatConvertImpl(const google::protobuf::stringpiece_internal::StringPiece&, const absl::lts_20211102::str_format_internal::FormatConversionSpecImpl&, absl::lts_20211102::str_format_internal::FormatSinkImpl*)’
  305 |       decltype(str_format_internal::FormatConvertImpl(
      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
  306 |           std::declval<const Arg&>(),
      |           ~~~~~~~~~~~~~~~~~~~~~~~~~~~
  307 |           std::declval<const FormatConversionSpecImpl&>(),
      |           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  308 |           std::declval<FormatSinkImpl*>())){});
      |           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
external/com_google_absl/absl/strings/internal/str_format/arg.h:60:6: note: candidate: ‘template<class T> decltype (absl::lts_20211102::str_format_internal::AbslFormatConvert(v, declval<const absl::lts_20211102::FormatConversionSpec&>(), declval<absl::lts_20211102::FormatSink*>())) absl::lts_20211102::str_format_internal::FormatConvertImpl(const T&, absl::lts_20211102::str_format_internal::FormatConversionSpecImpl, absl::lts_20211102::str_format_internal::FormatSinkImpl*)’
   60 | auto FormatConvertImpl(const T& v, FormatConversionSpecImpl conv,
      |      ^~~~~~~~~~~~~~~~~
```

I can confirm that this build "script" works on 0.1.75 and a number versions before that. Oddly enough the CPU-only build (run `nix-build -A python3Packages.jaxlib`) runs just fine.

- [x] If applicable, include full error messages/tracebacks.

You can check out the unabridged build log here: https://gist.github.com/samuela/fca69ea5ad0eb20d77b8be060446db21.

**Comment by hawkinsp** [comment]
Edit: with your versions, that might need to be:
```
return InvalidArgument("JSON parsing failed: %s", std::string{status.message()});
```

**Comment by samuela** [comment]
Thanks @hawkinsp! I'll try those modifications.

> This is related to your compiler. What compiler are you using?

This is GCC.

> your build script changes the JAX build to use a number of dependencies from the package manager, notably protobuf. I suspect that means it's a very different version to TF, which is currently stuck on a rather old protobuf for complicated reasons related to Windows builds.

Yeah, this is also suspect to me. IIUC we also build TF with this version of protobuf, but I think that may still be on TF v2.7.0. What versions of protobuf do you support building against?

**Comment by hawkinsp** [comment]
Let me know.

BTW, what version of gcc?

It's a bit complicated. We (personally) build/test in two configurations in our CI:
* open source, which uses a bundle of versions controlled via Bazel workspaces in the JAX and TF trees.
* our own internal builds, which is the same code, but the way it manages its dependencies is [quite different](https://research.google/pubs/pub45424/). The relevant thing here is that this is essentially "a different bundle of versions", whatever we have checked in at the tip of tree.

i.e., we have two different data points for versions of things where we know JAX builds and its tests pass.

It's possible everything works with both of those two exact sets of versions (e.g., all our CI builds pass) but not with a different bundle of versions (e.g., your build).

**Comment by samuela** [comment]
Not sure about the gcc version, but trying to figure it out: https://discourse.nixos.org/t/what-version-of-gcc-does-nix-use/17647

I have a [number of different protobuf versions](https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=protobuf) to play with. So I can simply switch to whatever version jaxlib requires to build. Are there some known good versions I ought to try?

**Comment by jonringer** [comment]
One oddity with cudatoolkits on nixpkgs is that they are opinionated about which versions of gcc they use: https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/compilers/cudatoolkit/default.nix

To ensure that you're using the same gcc version that was used in creation of the cudatoolkit, you could do something like:
```
let
  cudaStdenv = cudatoolkit_11_5.passthru.gcc.stdenv;
in
  cudaStdenv.mkDerivation rec {
    ...
```

**Comment by jonringer** [comment]
I also noticed `constexpr absl::lts_20211102` In the output.

Have to tried the older `abseil-cpp_202103` package?

**Comment by samuela** [comment]
@jonringer Looking at the derivation it seems the only dependency on absl is coming through `absl-py`, so I'm not sure if that's the issue. Is it possible for the absl cpp lib is coming through `absl-py`?

**Comment by samuela** [comment]
I found that protobuf 3.12 is the latest version that works.

**Comment by samuela** [comment]
I actually ended up going the patching route in https://github.com/NixOS/nixpkgs/commit/f3753388ad7291ee20f9bd07c25b9a66ed62269a. 
```
        substituteInPlace ../output/external/org_tensorflow/tensorflow/compiler/xla/python/pprof_profile_builder.cc \
           --replace "status.message()" "std::string{status.message()}"
```
worked like a charm!

Thanks everyone!

**Comment by hawkinsp** [comment]
@samuela I'll make that change upstream as well.

**Comment by hawkinsp** [comment]
Done in the TF repository. This isn't yet pulled into the jaxlib build—we need to update the pinned XLA (TF) version—but we'll certainly do that before the next release.

**Comment by samuela** [comment]
Great, thanks so much @hawkinsp !
