### ISSUE TITLE
jax2tf not working with conv got an unexpected keyword argument 'batch_group_count'

### ISSUE THREAD

**Issue by machineko** [google/jax#9384]
Please:

Following jax2tf tutorial

```python
(predict_fn, predict_params)  = mnist_flax.train()
input_signatures = [
    tf.TensorSpec((None,) + mnist_lib.input_shape, tf.float32),
]
saved_model_lib.convert_and_save_model(
        predict_fn,
        predict_params,
        "model",
        input_signatures=input_signatures,
        polymorphic_shapes="(batch, ...)",
        compile_model=False)
```

```
   1499 def gen_conv(lhs, rhs, preferred_element_type: Optional[DType]):
-> 1500   out = tfxla.conv(
   1501       lhs,
   1502       rhs,
   1503       window_strides,
   1504       padding,
   1505       lhs_dilation,
   1506       rhs_dilation,
   1507       dnums_proto,
   1508       feature_group_count=feature_group_count,
   1509       batch_group_count=batch_group_count,
   1510       precision_config=precision_config_proto,
   1511       preferred_element_type=preferred_element_type,
   1512       use_v2=True)
   1513   # TODO: implement shape inference for XlaConv
   1514   out.set_shape(out_tf_shape)

TypeError: conv() got an unexpected keyword argument 'batch_group_count'
```
jax, jaxlib and tf versions

Tested on both ubuntu 20.04 with cuda 11.5 and cudnn 8.2 and macos m1 with and without metal TF installed

![image](https://user-images.githubusercontent.com/42299606/151819971-5fc2f9cb-3573-4418-bf50-9c7c63576c93.png)

As i can see batch_group_count was added to xla.conv at 2.8 branch so it wouldnt work with stable tf (2.7) version https://github.com/tensorflow/tensorflow/commit/bfbb0595eee80f1032b44ced8de1eecf83d4c3c3 .
I have a small headache trying to debug it 😄 
So It is a bug? or should there only be a docs mention about that as jax isnt stable yet?

**Comment by gnecula** [comment]
Indeed, jax2tf works best with more recent versions of Tensorflow. I see that 2.8.0 is now the most recent version of TF. 

I will add a check for a better error message when using convolutions with batch_group_count with TF < 2.8.0.
