### ISSUE TITLE
Executing genrule @tsl//tsl/cuda:cudnn_stub_gen failed

### ISSUE THREAD

**Issue by adamjstewart** [google/jax#19992]
### Description

jaxlib does not build on PowerPC.

The error looks like:
```
ERROR: /tmp/spacky0n7oxbu/4310a55b80a5bf78e8b9018d02b90f5a/external/tsl/tsl/cuda/BUILD.bazel:132:10: Executing genrule @tsl//tsl/cuda:cudnn_stub_gen failed: (Exit 127): bash failed: error executing command (from target @tsl//tsl/cuda:cudnn_stub_gen)
...
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; NOT_IMPLEMENTED_FOR_THIS_PLATFORM_OR_ARCHITECTURE')
# Configuration: 3818a74cc7f5ae72cf721505511a1c130db9b4857cd3fc71c6ce848b0d2d8c55
# Execution platform: @local_execution_config_platform//:platform
/bin/bash: NOT_IMPLEMENTED_FOR_THIS_PLATFORM_OR_ARCHITECTURE: command not found
Target //jaxlib/tools:build_wheel failed to build
```
Build logs:

* [build log](https://github.com/google/jax/files/14417333/spack-build-out.txt)
* [build env](https://github.com/google/jax/files/14417332/spack-build-env-mods.txt)

### System info (python version, jaxlib version, accelerator, etc.)

* Python: 3.11.7
* Jaxlib: 0.4.25, 0.4.24
* Accelerator: N/A

**Comment by adamjstewart** [comment]
I tried an older version (0.4.16) and it has a different build error on ppc64le:
```
ERROR: /tmp/spackceyf0_mq/8d5f7252b6e3f5655299c7bc908f0f14/external/com_github_grpc_grpc/BUILD:1853:16: Compiling src/core/ext/transport/chttp2/client/secure/secure_channel_create.cc failed: (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command (from target @com_github_grpc_grpc//:grpc_transport_chttp2_client_secure)
...
In file included from external/boringssl/src/include/openssl/asn1.h:61,
                 from external/boringssl/src/include/openssl/x509.h:66,
                 from external/com_github_grpc_grpc/src/core/tsi/ssl_transport_security.h:28,
                 from external/com_github_grpc_grpc/src/core/lib/security/security_connector/security_connector.h:33,
                 from external/com_github_grpc_grpc/src/core/lib/security/credentials/credentials.h:35,
                 from external/com_github_grpc_grpc/src/core/ext/transport/chttp2/client/secure/secure_channel_create.cc:34:
external/boringssl/src/include/openssl/base.h:124:2: error: #error "Unknown target CPU"
  124 | #error "Unknown target CPU"
      |  ^~~~~
In file included from external/boringssl/src/include/openssl/asn1.h:66,
                 from external/boringssl/src/include/openssl/x509.h:66,
                 from external/com_github_grpc_grpc/src/core/tsi/ssl_transport_security.h:28,
                 from external/com_github_grpc_grpc/src/core/lib/security/security_connector/security_connector.h:33,
                 from external/com_github_grpc_grpc/src/core/lib/security/credentials/credentials.h:35,
                 from external/com_github_grpc_grpc/src/core/ext/transport/chttp2/client/secure/secure_channel_create.cc:34:
external/boringssl/src/include/openssl/bn.h:174:2: error: #error "Must define either OPENSSL_32_BIT or OPENSSL_64_BIT"
  174 | #error "Must define either OPENSSL_32_BIT or OPENSSL_64_BIT"
      |  ^~~~~
external/boringssl/src/include/openssl/bn.h:232:44: error: ‘BN_ULONG’ has not been declared
  232 | OPENSSL_EXPORT int BN_set_word(BIGNUM *bn, BN_ULONG value);
      |                                            ^~~~~~~~
...
```

**Comment by hawkinsp** [comment]
The code we use to call CUDA apis isn't implemented for the Power architecture.

To fix this, you'd need to do two things:
* add support for Power to this project: https://github.com/yugr/Implib.so . We use the stubs generated by implib.so for CUDA. This probably isn't that hard to do: you need to write a couple of short assembly snippets for that architecture though (https://github.com/yugr/Implib.so/tree/master/arch).
* update XLA's Bazel workspace to point to the new copy of implib.so, and add a case here: https://github.com/openxla/xla/blob/25e88c68b4c634ba4726b609b4d75377bb8aa0f5/xla/tsl/cuda/stub.bzl#L23

Contributions welcome! I don't personally have access to a Power-architecture VM, so it's hard for me to write such a change. But we'd welcome a PR!

**Comment by hawkinsp** [comment]
Filed https://github.com/yugr/Implib.so/issues/35 to track adding POWER support to that project.

The switch happened late September 2023, so I'd think that 0.4.16 was the last version without it.

**Comment by adamjstewart** [comment]
Hmm, 0.4.16 also failed for me on ppc, so it must be before that. I'll try slowly working backwards until I can find a version that builds.

Not sure if you want to keep this open or close it, I'll leave the decision up to you.

**Comment by hawkinsp** [comment]
I have no objection to leaving this open in case it helps anyone else trying to build on Power. But since we don't have such machines to test on, it's definitely in the "please send a PR" bucket.

**Comment by jazzisfuture** [comment]
I encountered the same issue while building on Windows.
```
C:\msys64\usr\bin\bash.exe -c source external/bazel_tools/tools/genrule/genrule-setup.sh; NOT_IMPLEMENTED_FOR_THIS_PLATFORM_OR_ARCHITECTURE
# Configuration: 495cec9c291802d357d888197346eec78634fd6511214ef107448eb12365f80e
# Execution platform: @local_execution_config_platform//:platform
/usr/bin/bash: line 1: NOT_IMPLEMENTED_FOR_THIS_PLATFORM_OR_ARCHITECTURE: command not found
Target //jaxlib/tools:build_wheel failed to build
INFO: Elapsed time: 20.333s, Critical Path: 1.42s
INFO: 231 processes: 203 internal, 28 local.
FAILED: Build did NOT complete successfully
ERROR: Build failed. Not running target
```

**Comment by hawkinsp** [comment]
@adamjstewart The commit above (at XLA head) may fix your problem. Give it a go!

(You'll need to override the XLA version used by jaxlib, see https://jax.readthedocs.io/en/latest/developer.html#building-jaxlib-from-source-with-a-modified-xla-repository until tomorrow when we'll automatically bump the XLA version.)

**Comment by adamjstewart** [comment]
Thanks! I likely won't get a chance to test this until your next release. I also don't have easy access to ppc64le, it's only in our CI.

**Comment by adamjstewart** [comment]
Just tried 0.4.26, unfortunately it also fails to build on ppc64le:
```
ERROR: /tmp/spack9k53xhil/557b6e16b5b46cba3da34154bbafae8a/external/curl/BUILD.bazel:26:11: Compiling lib/vtls/schannel_verify.c failed: (Exit 1): gcc failed: error executing command (from target @curl//:curl) 
...
# Configuration: a6dcb408019df56f52ddd35a52a3c00ef05719353a028bde66d77289343bb2f9
# Execution platform: @local_execution_config_platform//:platform
In file included from external/boringssl/src/include/openssl/crypto.h:18,
                 from external/boringssl/src/include/openssl/opensslv.h:18,
                 from bazel-out/ppc-opt/bin/external/curl/include/curl_config.h:5,
                 from external/curl/lib/curl_setup.h:78,
                 from external/curl/lib/vtls/schannel_verify.c:32:
external/boringssl/src/include/openssl/base.h:124:2: error: #error "Unknown target CPU"
  124 | #error "Unknown target CPU"
      |  ^~~~~
cc1: warning: unrecognized command line option '-Wno-string-plus-int'
cc1: warning: unrecognized command line option '-Wno-array-parameter'
cc1: warning: unrecognized command line option '-Wno-unknown-warning-option'
Target //jaxlib/tools:build_wheel failed to build
INFO: Elapsed time: 245.328s, Critical Path: 134.83s
INFO: 1168 processes: 601 internal, 567 local.
FAILED: Build did NOT complete successfully
ERROR: Build failed. Not running target
```
Full build log: [spack-build-out.txt](https://github.com/google/jax/files/14883879/spack-build-out.txt)

I realize this is a different dependency, so let me know if you want me to open a different issue. Ideally, we would be able to build with external copies of all of these dependencies so we don't have to keep bugging you every time one of them fails to build, but I don't see a way to do that.

**Comment by adamjstewart** [comment]
FWIW, jaxlib 0.4.3 is the most recent version that builds on ppc64le, 0.4.4+ all fail to build.

**Comment by hawkinsp** [comment]
You *can* use external system libraries rather than having us build them. See how the conda-forge build does it: https://github.com/conda-forge/jaxlib-feedstock/blob/044e3f94fb6231ae119caec9e6a663d2975180f0/recipe/build.sh#L82

(Not exactly documented by us, but it's infrastructure we share with XLA and TF.)

**Comment by adamjstewart** [comment]
@hawkinsp do you know where I can find the list of supported `TF_SYSTEM_LIBS` values?
