### ISSUE TITLE
Argument "out" of jnp.logical_and not exist

### ISSUE THREAD

**Issue by MarkusRabe** [google/jax#9119]
The [documentation](https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.logical_and.html) of `logical_and` claims that there is an argument called `out`, but this does not work apparently:

```python
from jax import numpy as jnp
arr = jnp.array([False, True, True, False])
jnp.logical_and(arr, arr, out=arr)

# TypeError: op() got an unexpected keyword argument 'out'
```

**Comment by jakevdp** [comment]
Thanks for the report – this is working as intended (`out` is not applicable to JAX functions because it involves mutating arrays) but recent changes have caused our docstring rewriting to fail; this was recently reported in #9090. I'll close this in favor of that issue.
