### ISSUE TITLE
from jax.sharding import Mesh fails with jax version 0.3.25

### ISSUE THREAD

**Issue by lucaslingle** [google/jax#14574]
### Description

I have been using a project with exact version dependencies specified in the ```setup.py``` file. However, today I am seeing that the project no longer works on any Cloud TPU v3 instances, due to an import error:

```
>>> from jax.sharding import Mesh
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'Mesh' from 'jax.sharding' (/home/lucaslingle/.local/lib/python3.8/site-packages/jax/sharding.py)
>>> 
KeyboardInterrupt
>>> 
```

I am unsure what has happened, as the jax version, jaxlib version, and libtpu version in the ```setup.py``` file are all the same as they have been for months, during which time the project worked fine. A ```pip freeze``` confirms the ```setup.py```-specified versions are the ones installed on the Cloud VM. 

It seems like bad practice for things to break in Jax without the version number changing, so I was hoping someone might be able help address this bug. Thanks!

### What jax/jaxlib version are you using?

jax v0.3.25, jaxlib v0.3.25, libtpu-nightly==0.1.dev20221109

### Which accelerator(s) are you using?

TPU

### Additional system info

Python version 3.8, Ubuntu 20.04.4 LTS (GNU/Linux 5.13.0-1027-gcp x86_64)

**Comment by lucaslingle** [comment]
Issue was due to a problem [elsewhere](https://github.com/google/orbax/issues/224), closing.
