### ISSUE TITLE
jaxlib cannot compile in version 0.1.47

### ISSUE THREAD

**Issue by qqsun8819** [google/jax#4704]
I'v encountered a compilation error when trying to compile jaxlib version 0.1.47 

## enviroments:

ubuntu 18.04
gcc version 7.5.0
conda python 3.7.9 

## steps to reproduce 

```
git checkout jaxlib-v0.1.47
python build/build.py
```

## errors:
```
ERROR: /root/.cache/bazel/_bazel_root/deb80d6610824a92deeac7b7fd0f3e3c/external/org_tensorflow/tensorflow/compiler/xla/python/BUILD:125:1: C++ compilation of rule '@org_tensorflo
w//tensorflow/compiler/xla/python:bfloat16' failed (Exit 1)
external/org_tensorflow/tensorflow/compiler/xla/python/bfloat16.cc: In function 'xla::StatusOr<pybind11::object> xla::Bfloat16Dtype()':
external/org_tensorflow/tensorflow/compiler/xla/python/bfloat16.cc:1483:41: warning: 'pybind11::object::object(pybind11::handle, bool)' is deprecated: Use reinterpret_borrow<obje
ct>() or reinterpret_steal<object>() [-Wdeprecated-declarations]
                     /*is_borrowed=*/true);
                                         ^
In file included from bazel-out/k8-opt/bin/external/pybind11/_virtual_includes/pybind11/pybind11/cast.h:13:0,
                 from bazel-out/k8-opt/bin/external/pybind11/_virtual_includes/pybind11/pybind11/attr.h:13,
                 from bazel-out/k8-opt/bin/external/pybind11/_virtual_includes/pybind11/pybind11/pybind11.h:44,
                 from external/org_tensorflow/tensorflow/compiler/xla/python/bfloat16.h:19,
                 from external/org_tensorflow/tensorflow/compiler/xla/python/bfloat16.cc:16:
bazel-out/k8-opt/bin/external/pybind11/_virtual_includes/pybind11/pybind11/pytypes.h:234:5: note: declared here
     object(handle h, bool is_borrowed) : handle(h) { if (is_borrowed) inc_ref(); }
     ^~~~~~
external/org_tensorflow/tensorflow/compiler/xla/python/bfloat16.cc: In instantiation of 'bool xla::{anonymous}::RegisterUFunc(PyObject*, const char*) [with UFunc = xla::{anonymou
s}::BinaryUFunc<tensorflow::bfloat16, tensorflow::bfloat16, xla::{anonymous}::ufuncs::Add>; PyObject = _object]':
external/org_tensorflow/tensorflow/compiler/xla/python/bfloat16.cc:1321:72:   required from here
external/org_tensorflow/tensorflow/compiler/xla/python/bfloat16.cc:775:26: error: invalid conversion from 'void (*)(char**, npy_intp*, npy_intp*, void*) {aka void (*)(char**, lon
g int*, long int*, void*)}' to 'PyUFuncGenericFunction {aka void (*)(char**, const long int*, const long int*, void*)}' [-fpermissive]
   PyUFuncGenericFunction fn = UFunc::Call;
                          ^~
external/org_tensorflow/tensorflow/compiler/xla/python/bfloat16.cc: In instantiation of 'bool xla::{anonymous}::RegisterUFunc(PyObject*, const char*) [with UFunc = xla::{anonymou
s}::BinaryUFunc<tensorflow::bfloat16, tensorflow::bfloat16, xla::{anonymous}::ufuncs::Subtract>; PyObject = _object]':
external/org_tensorflow/tensorflow/compiler/xla/python/bfloat16.cc:1323:34:   required from here
external/org_tensorflow/tensorflow/compiler/xla/python/bfloat16.cc:775:26: error: invalid conversion from 'void (*)(char**, npy_intp*, npy_intp*, void*) {aka void (*)(char**, lon
g int*, long int*, void*)}' to 'PyUFuncGenericFunction {aka void (*)(char**, const long int*, const long int*, void*)}' [-fpermissive]
external/org_tensorflow/tensorflow/compiler/xla/python/bfloat16.cc: In instantiation of 'bool xla::{anonymous}::RegisterUFunc(PyObject*, const char*) [with UFunc = xla::{anonymou
s}::BinaryUFunc<tensorflow::bfloat16, tensorflow::bfloat16, xla::{anonymous}::ufuncs::Multiply>; PyObject = _object]':
external/org_tensorflow/tensorflow/compiler/xla/python/bfloat16.cc:1325:34:   required from here
external/org_tensorflow/tensorflow/compiler/xla/python/bfloat16.cc:775:26: error: invalid conversion from 'void (*)(char**, npy_intp*, npy_intp*, void*) {aka void (*)(char**, lon
g int*, long int*, void*)}' to 'PyUFuncGenericFunction {aka void (*)(char**, const long int*, const long int*, void*)}' [-fpermissive]
external/org_tensorflow/tensorflow/compiler/xla/python/bfloat16.cc: In instantiation of 'bool xla::{anonymous}::RegisterUFunc(PyObject*, const char*) [with UFunc = xla::{anonymou
s}::BinaryUFunc<tensorflow::bfloat16, tensorflow::bfloat16, xla::{anonymous}::ufuncs::TrueDivide>; PyObject = _object]':
external/org_tensorflow/tensorflow/compiler/xla/python/bfloat16.cc:1327:32:   required from here
```

I can compile successfully in jax newest  master  branch(version 0.1.56)
so I wonder where is the problem

**Comment by jekbradbury** [comment]
I'm curious why you need such an old version?

**Comment by hawkinsp** [comment]
We aren't going to fix build errors in older versions when the newer version builds successfully...

I suggest using a newer version of jaxlib.
