### ISSUE TITLE
AttributeError: module 'jax' has no attribute 'debug'

### ISSUE THREAD

**Issue by coderlemon17** [google/jax#11683]
Hi, I'm new to Jax and following the tutorial when I find that there's no `debug` package in my installed Jax. 
```python
import jax
import jax.numpy as jnp

@jax.jit
def f(x):
  jax.debug.print("🤯 {x} 🤯", x=x)
  y = jnp.sin(x)
  jax.debug.print("🤯 {y} 🤯", y=y)
  return y
  
f(2.)
>>> AttributeError: module 'jax' has no attribute 'debug'
```
But I think I should have installed the latest version of Jax:
```shell
$ pip list | grep jax                               
jax                  0.3.15
jaxlib               0.3.15+cuda11.cudnn82
$ cat /proc/version
Linux version 5.16.0-0.bpo.4-amd64 (debian-kernel@lists.debian.org) (gcc-10 (Debian 10.2.1-6) 10.2.1 20210110, GNU ld (GNU Binutils for Debian) 2.35.2) #1 SMP PREEMPT Debian 5.16.12-1~bpo11+1 (2022-03-08)
```
And I'm using CUDA11.1 with cuDNN8.2.1.

**Comment by soraros** [comment]
The `debug` module is introduced in #11653, which is only available for JAX 0.3.16+(I think) or master.

**Comment by sharadmv** [comment]
Yes the debug tools are available at HEAD but not yet in a release. We'll cut a release soon.

**Comment by coderlemon17** [comment]
Thanks for the info, I didn't realize that it is a new feature. Looking forward to the release.
