### ISSUE TITLE
Jaxlib 0.1.68 Fails to Build on Windows

### ISSUE THREAD

**Issue by oracle3001** [google/jax#7079]
With Python 3.8, Cuda 11.2, Bazel 4.1, build run with the following command

`python .\build\build.py --enable_cuda --cuda_path="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.2" --cudnn_path="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.2" --cuda_compute_capabilities="7.5" --cuda_version="11.2" --cudnn_version="8.1.0" --noenable_rocm --noenable_tpu`

results in the following error.

```
ERROR: C:/users/adam/_bazel_adam/n5urqa67/external/org_tensorflow/tensorflow/compiler/xla/pjrt/BUILD:372:11: Compiling tensorflow/compiler/xla/pjrt/tracked_tfrt_cpu_device_buffer.cc failed: (Exit 2): python.exe failed: error executing command
  cd C:/users/adam/_bazel_adam/n5urqa67/execroot/__main__
  SET CUDA_TOOLKIT_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.2
    SET CUDNN_INSTALL_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.2
    SET INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30037\ATLMFC\include;C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30037\include;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared;C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt
    SET LIB=C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30037\ATLMFC\lib\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30037\lib\x64;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\ucrt\x64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\um\x64
    SET PATH=C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\\Extensions\Microsoft\IntelliCode\CLI;C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30037\bin\HostX64\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\bin\Roslyn;C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Team Tools\Performance Tools\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Team Tools\Performance Tools;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\vs2019\\x64;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\vs2019\;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\x64\;C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\devinit;C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x64;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\\MSBuild\Current\Bin;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\;;C:\WINDOWS\system32;C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja
    SET PWD=/proc/self/cwd
    SET RUNFILES_MANIFEST_ONLY=1
    SET TEMP=C:\Users\Adam\AppData\Local\Temp
    SET TF_CUDA_COMPUTE_CAPABILITIES=7.5
    SET TF_CUDA_VERSION=11.2
    SET TF_CUDNN_VERSION=8.1.0
    SET TF_ROCM_AMDGPU_TARGETS=gfx803,gfx900,gfx906,gfx1010
    SET TMP=C:\Users\Adam\AppData\Local\Temp
  C:/Users/Adam/anaconda3/envs/tensorflow/python.exe -B external/local_config_cuda/crosstool/windows/msvc_wrapper_for_nvcc.py /nologo /DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0600 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_SECURE_NO_WARNINGS /D_SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS /bigobj /Zm500 /J /Gy /GF /EHsc /wd4351 /wd4291 /wd4250 /wd4996 /Iexternal/org_tensorflow /Ibazel-out/x64_windows-opt/bin/external/org_tensorflow /Iexternal/eigen_archive /Ibazel-out/x64_windows-opt/bin/external/eigen_archive /Iexternal/com_google_absl /Ibazel-out/x64_windows-opt/bin/external/com_google_absl /Iexternal/nsync /Ibazel-out/x64_windows-opt/bin/external/nsync /Iexternal/gif /Ibazel-out/x64_windows-opt/bin/external/gif /Iexternal/libjpeg_turbo /Ibazel-out/x64_windows-opt/bin/external/libjpeg_turbo /Iexternal/com_google_protobuf /Ibazel-out/x64_windows-opt/bin/external/com_google_protobuf /Iexternal/com_googlesource_code_re2 /Ibazel-out/x64_windows-opt/bin/external/com_googlesource_code_re2 /Iexternal/farmhash_archive /Ibazel-out/x64_windows-opt/bin/external/farmhash_archive /Iexternal/fft2d /Ibazel-out/x64_windows-opt/bin/external/fft2d /Iexternal/highwayhash /Ibazel-out/x64_windows-opt/bin/external/highwayhash /Iexternal/zlib /Ibazel-out/x64_windows-opt/bin/external/zlib /Iexternal/double_conversion /Ibazel-out/x64_windows-opt/bin/external/double_conversion /Iexternal/snappy /Ibazel-out/x64_windows-opt/bin/external/snappy /Iexternal/tf_runtime /Ibazel-out/x64_windows-opt/bin/external/tf_runtime /Iexternal/llvm-project /Ibazel-out/x64_windows-opt/bin/external/llvm-project /Iexternal/org_tensorflow/third_party/eigen3/mkl_include /Ibazel-out/x64_windows-opt/bin/external/org_tensorflow/third_party/eigen3/mkl_include /Iexternal/eigen_archive /Ibazel-out/x64_windows-opt/bin/external/eigen_archive /Iexternal/nsync/public /Ibazel-out/x64_windows-opt/bin/external/nsync/public /Iexternal/gif /Ibazel-out/x64_windows-opt/bin/external/gif /Iexternal/gif/windows /Ibazel-out/x64_windows-opt/bin/external/gif/windows /Iexternal/com_google_protobuf/src /Ibazel-out/x64_windows-opt/bin/external/com_google_protobuf/src /Iexternal/farmhash_archive/src /Ibazel-out/x64_windows-opt/bin/external/farmhash_archive/src /Iexternal/zlib /Ibazel-out/x64_windows-opt/bin/external/zlib /Iexternal/double_conversion /Ibazel-out/x64_windows-opt/bin/external/double_conversion /Iexternal/tf_runtime/include /Ibazel-out/x64_windows-opt/bin/external/tf_runtime/include /Iexternal/llvm-project/llvm/include /Ibazel-out/x64_windows-opt/bin/external/llvm-project/llvm/include /Iexternal/tf_runtime/third_party/llvm_derived/include /Ibazel-out/x64_windows-opt/bin/external/tf_runtime/third_party/llvm_derived/include /DEIGEN_MPL2_ONLY /DEIGEN_MAX_ALIGN_BYTES=64 /DTF_USE_SNAPPY /D_CRT_SECURE_NO_DEPRECATE /D_CRT_SECURE_NO_WARNINGS /D_CRT_NONSTDC_NO_DEPRECATE /D_CRT_NONSTDC_NO_WARNINGS /D_SCL_SECURE_NO_DEPRECATE /D_SCL_SECURE_NO_WARNINGS /DUNICODE /D_UNICODE /DLLVM_ENABLE_STATS /D__STDC_LIMIT_MACROS /D__STDC_CONSTANT_MACROS /D__STDC_FORMAT_MACROS /DLLVM_BUILD_GLOBAL_ISEL /showIncludes /MD /O2 /DNDEBUG /D_USE_MATH_DEFINES -DWIN32_LEAN_AND_MEAN -DNOGDI /Zc:preprocessor /std:c++14 /Fobazel-out/x64_windows-opt/bin/external/org_tensorflow/tensorflow/compiler/xla/pjrt/_objs/tracked_tfrt_cpu_device_buffer/tracked_tfrt_cpu_device_buffer.obj /c external/org_tensorflow/tensorflow/compiler/xla/pjrt/tracked_tfrt_cpu_device_buffer.cc
Execution platform: @local_execution_config_platform//:platform
Target //build:build_wheel failed to build
INFO: Elapsed time: 1710.423s, Critical Path: 331.72s
INFO: 6277 processes: 2542 internal, 3735 local.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
b"external/llvm-project/llvm/include\\llvm/Support/type_traits.h(79): warning C4624: 'llvm::detail::copy_construction_triviality_helper<T>': destructor was implicitly defined as deleted\r\n        with\r\n        [\r\n            T=std::string\r\n        ]\r\nC:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Tools\\MSVC\\14.29.30037\\include\\type_traits(631): note: see reference to class template instantiation 'llvm::detail::copy_construction_triviality_helper<T>' being compiled\r\n        with\r\n        [\r\n            T=std::string\r\n        ]\r\nexternal/llvm-project/llvm/include\\llvm/Support/type_traits.h(100): note: see reference to class template instantiation 'std::is_copy_constructible<llvm::detail::copy_construction_triviality_helper<T>>' being compiled\r\n        with\r\n        [\r\n            T=std::string\r\n        ]\r\nexternal/llvm-project/llvm/include\\llvm/ADT/SmallVector.h(311): note: see reference to class template instantiation 'llvm::is_trivially_copy_constructible<T>' being compiled\r\n        with\r\n        [\r\n            T=std::string\r\n        ]\r\nexternal/llvm-project/llvm/include\\llvm/ADT/SmallVector.h(1167): note: see reference to class template instantiation 'llvm::SmallVectorImpl<T>' being compiled\r\n        with\r\n        [\r\n            T=std::string\r\n        ]\r\nexternal/llvm-project/llvm/include\\llvm/Support/Error.h(992): note: see reference to class template instantiation 'llvm::SmallVector<std::string,2>' being compiled\r\nexternal/llvm-project/llvm/include\\llvm/Support/type_traits.h(86): warning C4624: 'llvm::detail::move_construction_triviality_helper<T>': destructor was implicitly defined as deleted\r\n        with\r\n        [\r\n            T=std::string\r\n        ]\r\nC:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Tools\\MSVC\\14.29.30037\\include\\type_traits(662): note: see reference to class template instantiation 'llvm::detail::move_construction_triviality_helper<T>' being compiled\r\n        with\r\n        [\r\n            T=std::string\r\n        ]\r\nexternal/llvm-project/llvm/include\\llvm/Support/type_traits.h(111): note: see reference to class template instantiation 'std::is_move_constructible<llvm::detail::move_construction_triviality_helper<T>>' being compiled\r\n        with\r\n        [\r\n            T=std::string\r\n        ]\r\nexternal/llvm-project/llvm/include\\llvm/ADT/SmallVector.h(311): note: see reference to class template instantiation 'llvm::is_trivially_move_constructible<T>' being compiled\r\n        with\r\n        [\r\n            T=std::string\r\n        ]\r\nexternal/llvm-project/llvm/include\\llvm/Support/type_traits.h(79): warning C4624: 'llvm::detail::copy_construction_triviality_helper<T>': destructor was implicitly defined as deleted\r\n        with\r\n        [\r\n            T=tfrt::DebugInfo\r\n        ]\r\nC:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Tools\\MSVC\\14.29.30037\\include\\type_traits(631): note: see reference to class template instantiation 'llvm::detail::copy_construction_triviality_helper<T>' being compiled\r\n        with\r\n        [\r\n            T=tfrt::DebugInfo\r\n        ]\r\nexternal/llvm-project/llvm/include\\llvm/Support/type_traits.h(100): note: see reference to class template instantiation 'std::is_copy_constructible<llvm::detail::copy_construction_triviality_helper<T>>' being compiled\r\n        with\r\n        [\r\n            T=tfrt::DebugInfo\r\n        ]\r\nexternal/llvm-project/llvm/include\\llvm/ADT/Optional.h(53): note: see reference to class template instantiation 'llvm::is_trivially_copy_constructible<T>' being compiled\r\n        with\r\n        [\r\n            T=tfrt::DebugInfo\r\n        ]\r\nexternal/tf_runtime/include\\tfrt/host_context/location.h(83): note: see reference to class template instantiation 'llvm::Optional<tfrt::DebugInfo>' being compiled\r\nexternal/llvm-project/llvm/include\\llvm/Support/type_traits.h(79): warning C4624: 'llvm::detail::copy_construction_triviality_helper<T>': destructor was implicitly defined as deleted\r\n        with\r\n        [\r\n            T=std::unique_ptr<tfrt::BaseTypedErrorInfo,std::default_delete<tfrt::BaseTypedErrorInfo>>\r\n        ]\r\nC:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Tools\\MSVC\\14.29.30037\\include\\type_traits(631): note: see reference to class template instantiation 'llvm::detail::copy_construction_triviality_helper<T>' being compiled\r\n        with\r\n        [\r\n            T=std::unique_ptr<tfrt::BaseTypedErrorInfo,std::default_delete<tfrt::BaseTypedErrorInfo>>\r\n        ]\r\nexternal/llvm-project/llvm/include\\llvm/Support/type_traits.h(100): note: see reference to class template instantiation 'std::is_copy_constructible<llvm::detail::copy_construction_triviality_helper<T>>' being compiled\r\n        with\r\n        [\r\n            T=std::unique_ptr<tfrt::BaseTypedErrorInfo,std::default_delete<tfrt::BaseTypedErrorInfo>>\r\n        ]\r\nexternal/llvm-project/llvm/include\\llvm/ADT/SmallVector.h(311): note: see reference to class template instantiation 'llvm::is_trivially_copy_constructible<T>' being compiled\r\n        with\r\n        [\r\n            T=std::unique_ptr<tfrt::BaseTypedErrorInfo,std::default_delete<tfrt::BaseTypedErrorInfo>>\r\n        ]\r\nexternal/llvm-project/llvm/include\\llvm/ADT/SmallVector.h(1167): note: see reference to class template instantiation 'llvm::SmallVectorImpl<T>' being compiled\r\n        with\r\n        [\r\n            T=std::unique_ptr<tfrt::BaseTypedErrorInfo,std::default_delete<tfrt::BaseTypedErrorInfo>>\r\n        ]\r\nexternal/tf_runtime/include\\tfrt/support/error_util.h(255): note: see reference to class template instantiation 'llvm::SmallVector<std::unique_ptr<tfrt::BaseTypedErrorInfo,std::default_delete<tfrt::BaseTypedErrorInfo>>,4>' being compiled\r\nexternal/llvm-project/llvm/include\\llvm/Support/type_traits.h(86): warning C4624: 'llvm::detail::move_construction_triviality_helper<T>': destructor was implicitly defined as deleted\r\n        with\r\n        [\r\n            T=std::unique_ptr<tfrt::BaseTypedErrorInfo,std::default_delete<tfrt::BaseTypedErrorInfo>>\r\n        ]\r\nC:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Tools\\MSVC\\14.29.30037\\include\\type_traits(662): note: see reference to class template instantiation 'llvm::detail::move_construction_triviality_helper<T>' being compiled\r\n        with\r\n        [\r\n            T=std::unique_ptr<tfrt::BaseTypedErrorInfo,std::default_delete<tfrt::BaseTypedErrorInfo>>\r\n        ]\r\nexternal/llvm-project/llvm/include\\llvm/Support/type_traits.h(111): note: see reference to class template instantiation 'std::is_move_constructible<llvm::detail::move_construction_triviality_helper<T>>' being compiled\r\n        with\r\n        [\r\n            T=std::unique_ptr<tfrt::BaseTypedErrorInfo,std::default_delete<tfrt::BaseTypedErrorInfo>>\r\n        ]\r\nexternal/llvm-project/llvm/include\\llvm/ADT/SmallVector.h(311): note: see reference to class template instantiation 'llvm::is_trivially_move_constructible<T>' being compiled\r\n        with\r\n        [\r\n            T=std::unique_ptr<tfrt::BaseTypedErrorInfo,std::default_delete<tfrt::BaseTypedErrorInfo>>\r\n        ]\r\nexternal/llvm-project/llvm/include\\llvm/Support/type_traits.h(79): warning C4624: 'llvm::detail::copy_construction_triviality_helper<T>': destructor was implicitly defined as deleted\r\n        with\r\n        [\r\n            T=tfrt::DecodedLocation\r\n        ]\r\nC:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Tools\\MSVC\\14.29.30037\\include\\type_traits(631): note: see reference to class template instantiation 'llvm::detail::copy_construction_triviality_helper<T>' being compiled\r\n        with\r\n        [\r\n            T=tfrt::DecodedLocation\r\n        ]\r\nexternal/llvm-project/llvm/include\\llvm/Support/type_traits.h(100): note: see reference to class template instantiation 'std::is_copy_constructible<llvm::detail::copy_construction_triviality_helper<T>>' being compiled\r\n        with\r\n        [\r\n            T=tfrt::DecodedLocation\r\n        ]\r\nexternal/llvm-project/llvm/include\\llvm/ADT/Optional.h(53): note: see reference to class template instantiation 'llvm::is_trivially_copy_constructible<T>' being compiled\r\n        with\r\n        [\r\n            T=tfrt::DecodedLocation\r\n        ]\r\nexternal/tf_runtime/include\\tfrt/host_context/diagnostic.h(48): note: see reference to class template instantiation 'llvm::Optional<tfrt::DecodedLocation>' being compiled\r\nexternal/tf_runtime/include\\tfrt/host_context/async_value.h(455): error C2338: Unexpected size for AsyncValue\r\n"
Traceback (most recent call last):
  File ".\build\build.py", line 564, in <module>
    main()
  File ".\build\build.py", line 559, in main
    shell(command)
  File ".\build\build.py", line 52, in shell
    output = subprocess.check_output(cmd)
  File "C:\Users\Adam\anaconda3\envs\tensorflow\lib\subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\Adam\anaconda3\envs\tensorflow\lib\subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\bazel\\bazel.EXE', 'run', '--verbose_failures=true', '--config=short_logs', '--config=mkl_open_source_only', '--config=cuda', '--define=xla_python_enable_gpu=true', ':build_wheel', '--', '--output_path=C:\\sdks\\jax-jaxlib-v0.1.68\\dist']' returned non-zero exit status 1.
```

**Comment by jakevdp** [comment]
cross-ref #6637

**Comment by zhangqiaorjc** [comment]
We didn't actually fix windows build in between 0.1.66 and 0.1.68 due to limited bandwidth, but we did add something to the build script to print out the compilation error -- the long string starting with `b"external/llvm-project...`

I can now forward the compiler error messages to my TFRT coworkers and see if they can push a fix in TFRT codebase.

**Comment by zhangqiaorjc** [comment]
the actual error is that this static_assert failed

external/tf_runtime/include\tfrt/host_context/async_value.h(455): error C2338: Unexpected size for AsyncValue

The code is 
```
// We only optimize the code for 64-bit architectures for now.
static_assert(sizeof(AsyncValue) == 16 || sizeof(void*) != 8,
              "Unexpected size for AsyncValue");
```

https://github.com/tensorflow/runtime/blob/master/include/tfrt/host_context/async_value.h#L455

@oracle3001 unfortunately we can't tell what values does `sizeof(AsyncValue)` and `sizeof(void*)` get. Can you tell us what you are seeing for these two values? You can checkout tfrt and just bazel build `hostcontext` 

https://github.com/tensorflow/runtime/blob/master/BUILD#L113

**Comment by oracle3001** [comment]
I have built the runtime code. Where do I look for the sizeof(AsyncValue) and sizeof(void*) ?

**Comment by zhangqiaorjc** [comment]
The new error messages are for some other reasons...you can probably do just `bazel build //:hostcontext` since JAX doesn't depend on `//tools:` and get the exact same compilation error.

There might be a simpler way to check. Can you just run this C++ program?

$ cat sc.cc
#include <cstdio>
int main() {
  printf("sizeof(void*)=%d\n", sizeof(void*));
}
$ make sc
g++     sc.cc   -o sc
$ ./sc
sizeof(void*)=8

This will help us distinguish `sizeof(AsyncValue) == 16 || sizeof(void*) != 8`. I suspect it's because sizeof(AsyncValue) != 16 on your machine.

It's likely that on Windows, AsyncValue struct layout isn't exactly the same as we expect on Linux. 

I just remembered the issues in https://github.com/google/jax/issues/6637#issuecomment-855164868

If so, we might need a few iterations to fix this issue in TFRT codebase...

**Comment by zhangqiaorjc** [comment]
Let's also wait for this PR to land: https://github.com/tensorflow/runtime/pull/60

It should fix some of those Windows build issues due to TFRT

**Comment by oracle3001** [comment]
From creating the suggested test application.

"sizeof(void*)=8"

**Comment by cloudhan** [comment]
I have successfully produce a jaxlib whl with local tensorflow repo] of commit [8557ca660](https://github.com/tensorflow/tensorflow/tree/8557ca660aa7b1d5853d3a1f2fe19cae5be4b589)

**Comment by oracle3001** [comment]
FYI, jaxlib 0.1.69 now builds out the box for me.

**Comment by softworkz** [comment]
@oracle3001 - How?

Which versions of python, CUDA cuDNN, bazel?
Which command line?

Thanks

**Comment by oracle3001** [comment]
> @oracle3001 - How?
> 
> Which versions of python, CUDA cuDNN, bazel?
> Which command line?
> 
> Thanks

Python 3.8, Cuda 11.2, cuDNN 8.1.0, Bazel 4.1

Run with the following build command.

`python .\build\build.py --enable_cuda --cuda_path="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.2" --cudnn_path="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.2" --cuda_compute_capabilities="7.5" --cuda_version="11.2" --cudnn_version="8.1.0" --noenable_rocm --noenable_tpu`

**Comment by softworkz** [comment]
Thanks. I tried so many combinations, but here it always fails when trying to download a non-existing TF archive:

`UnrecoverableHttpException GET returned 404 Not Found`

followed by 

`ERROR: An error occurred during the fetch of repository 'local_config_cuda':`


```
INFO: Found applicable config definition build:windows in file f:\projects\ai\jax\.bazelrc: --copt=/D_USE_MATH_DEFINES --host_copt=/D_USE_MATH_DEFINES --copt=-DWIN32_LEAN_AND_MEAN --host_copt=-DWIN32_LEAN_AND_MEAN --copt=-DNOGDI --host_copt=-DNOGDI --copt=/Zc:preprocessor --cxxopt=/std:c++14 --host_cxxopt=/std:c++14 --linkopt=/DEBUG --host_linkopt=/DEBUG --linkopt=/OPT:REF --host_linkopt=/OPT:REF --linkopt=/OPT:ICF --host_linkopt=/OPT:ICF --experimental_strict_action_env=true
WARNING: Download from http://mirror.tensorflow.org/github.com/tensorflow/runtime/archive/d29d1ef0a65a8f9c23e1f88067ce4205d3085e87.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
INFO: Repository local_config_cuda instantiated at:
  F:/projects/ai/jax/WORKSPACE:30:10: in <toplevel>
  C:/users/admin/_bazel_admin/avp2whpv/external/org_tensorflow/tensorflow/workspace2.bzl:1085:19: in workspace
  C:/users/admin/_bazel_admin/avp2whpv/external/org_tensorflow/tensorflow/workspace2.bzl:90:19: in _tf_toolchains
Repository rule cuda_configure defined at:
  C:/users/admin/_bazel_admin/avp2whpv/external/org_tensorflow/third_party/gpus/cuda_configure.bzl:1448:33: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_config_cuda':
   Traceback (most recent call last):
        File "C:/users/admin/_bazel_admin/avp2whpv/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 1401, column 38, in _cuda_autoconf_impl
                _create_local_cuda_repository(repository_ctx)
        File "C:/users/admin/_bazel_admin/avp2whpv/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 1239, column 56, in _create_local_cuda_repository
                host_compiler_includes + _cuda_include_path(
        File "C:/users/admin/_bazel_admin/avp2whpv/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 364, column 32, in _cuda_include_path
                inc_entries.append(realpath(repository_ctx, cuda_config.cuda_toolkit_path + "/include"))
        File "C:/users/admin/_bazel_admin/avp2whpv/external/org_tensorflow/third_party/remote_config/common.bzl", line 290, column 19, in realpath
                return execute(repository_ctx, [bash_bin, "-c", "realpath \"%s\"" % path]).stdout.strip()
        File "C:/users/admin/_bazel_admin/avp2whpv/external/org_tensorflow/third_party/remote_config/common.bzl", line 230, column 13, in execute
                fail(
Error in fail: Repository command failed
realpath: 'C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.2/include': No such file or directory
ERROR: Error fetching repository: Traceback (most recent call last):
 
```

**Comment by hawkinsp** [comment]
The TF archive download failure is a warning and benign. Ignore it.

The issue is probably related to not finding your CUDA toolkit, which is the fatal error above.

**Comment by softworkz** [comment]
Thanks @hawkinsp, I figured it out: I've been re-using an existing MSYS2 installation which seems to have some conflicting configuration. Installed a fresh MSYS2 and it's building now!

Thanks a lot for your assistance (to both of you)!

**Comment by gcusso** [comment]
@oracle3001 Could you upload the jaxlib.whl file from you last successful build?

Thanks!

**Comment by GMCobraz** [comment]
Hi guys, 

I saw @oracle3001 succefully build the jaxlib with python 3.8, cuda v11.2, cudnn v8.1.

I suspect this is due to the gcc and g++ version from msys2.
If we check the gcc version from msys2 or cmd. We found out that the gcc version show is v10.

I tried install cuda in ubuntu too, with cuda v10.1, cudnn v7.6.5.
**I remember the gcc and g++ version must be v8.**
It will have error when gcc & g++ version larger than 8.

So I suspect this is the issue if someone try to build jaxlib with cuda v10.1, cudnn v7.6.5 will fail due to incompatible gcc & g++ version.
Maybe cuda v11.2, cudnn v8.1 are running fine with gcc & g++ version 10.

This is my hypothesis only.
Can any experts please verify whether what I claim is correct or wrong?
Is there a ways to install specific version of gcc and g++ in msys2?
I checked and it seems like msys2 didn't keep many archieve.

Thank you very much.

**Comment by GMCobraz** [comment]
Hi @oracle3001 ,

May I know did you solved the failed to build error at the end?

Thank you very much

**Comment by hawkinsp** [comment]
@GMCobraz can you share the complete logs from your build?

Note that gcc versions are irrelevant on Windows; JAX should be built with MSVC, per the instructions (https://jax.readthedocs.io/en/latest/developer.html#additional-notes-for-building-jaxlib-from-source-on-windows).

**Comment by GMCobraz** [comment]
Hi @hawkinsp ,
Good day.
Here attached with my error log.
![image](https://user-images.githubusercontent.com/63672255/125844253-088ae598-92ac-43b0-a10e-4917ff8301ad.png)
![image](https://user-images.githubusercontent.com/63672255/125844413-8349b766-fb64-4c22-b12f-71c259b880bf.png)

I built JAX with MSVC, but not sure why it still fail
Please help. thanks.

**Comment by cloudhan** [comment]
@GMCobraz Windows is not an officially supported platform (at least currently), so you should not expect support from them. This [PR](https://github.com/google/jax/pull/7319) should resolve you problem.

**Comment by cloudhan** [comment]
I was trying to set up third party CI for windows build, but lack for compute resource now.

The following are try-out builds last weekend, manually.

#### CUDA 10.1

*contains fix from the previously mentioned PR*

https://whls.blob.core.windows.net/cuda101/jaxlib-0.1.70+cuda101-cp37-none-win_amd64.whl
https://whls.blob.core.windows.net/cuda101/jaxlib-0.1.70+cuda101-cp38-none-win_amd64.whl
https://whls.blob.core.windows.net/cuda101/jaxlib-0.1.70+cuda101-cp39-none-win_amd64.whl

#### CUDA 11.2

https://whls.blob.core.windows.net/cuda112/jaxlib-0.1.70+cuda112-cp37-none-win_amd64.whl
https://whls.blob.core.windows.net/cuda112/jaxlib-0.1.70+cuda112-cp38-none-win_amd64.whl
https://whls.blob.core.windows.net/cuda112/jaxlib-0.1.70+cuda112-cp39-none-win_amd64.whl

If you trust me, use it. Otherwise, leave alone.

**Comment by GMCobraz** [comment]
Hi @cloudhan ,

Thanks for the reply.
Once I downloaded the .whl file, I can proceed with numpyro v0.7.1 installation right? 

May I have the jaxlib-0.1.62+cuda101-cp37-none-win_amd64.whl?
Cause I will need it to install with numypro v0.6.0 and jax v0.2.10.
Thank you very much

**Comment by cloudhan** [comment]
You can try it out, that is, new version `jaxlib` + old version `jax`, not sure will it works.

**Comment by hawkinsp** [comment]
I believe this issue is already resolved. Closing. Feel free to open new issues for new problems. Thanks for all the help everyone!
